### PR TITLE
Serializable state for non-INVITE transactions

### PR DESCRIPTION
**Pull request by hagane**
Non-INVITE client and server transactions were refactored similarly to INVITE transactions.

### CODE REVIEW

**Comment by poroh** [comment]
I really do not like internal imports. Why do you need this state? For logging purposes?

**Comment by hagane** [comment]
I agree, it does not looks particularly elegant. I just thought that is the accepted solution.

We need to keep all the accumulated transaction state when the application is restarted and having a function reference as a state is not really conducive to that end.
It could be redone without internal exports -- by replacing generic clause in `process_event/2` with several specific ones. Would that be more correct?

**Comment by poroh** [comment]
I would rather prefer to have save_state and restore_state functions that are independent from internal implementation and guarantee contract with outside world.

**Comment by hagane** [comment]
I agree, having dedicated functions is a far better solution. But I think these functions should be named `to_map` and `from_map` or something like that. That way their names would describe what they actually do and would not conflate the meaning with actually storing the results somewhere.

**Comment by poroh** [comment]
If you want to restore transaction you also need to restore timers somehow. So code of restoration could be more tricky than just restore from serialized object. Also it looks like no needs to save transactions in completed state because they will die very soon unless your application restart is shorter than 4 seconds (T2 default timeout).

**Comment by hagane** [comment]
Of course we will need to restore timers too. And it is definitely going to be a quite intricate process. But that's something we'll have to deal with.

**Comment by hagane** [comment]
I've added `to_map` and `from_map` functions as we discussed.

**Comment by poroh** [comment]
Thank you for your contribution!

**Pull request merged**
